import { Inter } from 'next/font/google'
import '../css/globals.css'
import { AxiomWebVitals } from 'next-axiom'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'League of Stats',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <AxiomWebVitals />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
